export default {
  colors: {
    lightColor: '#FFFFFF',
    primaryColorLight: '#FFE9E0',
    primaryColor: '#FA641E',
    secondaryColor: '#18AA36',
    colorPrimaryText: '#4B4B4B',
    error: '#E03222',
    errorLight: '#f77',
    background: '#F9F9F9',
    disableColor: '#dcdcdc',
    defaultText: '#222222',
    ValuePrice: '#333',
    defaultTextDescription: '#676767',
    disableText: '#999999',
    disableButton: '#EEEEEE',
    borderColor: '#DDDDDD',
    SixSix: '#666666',
    borderColorButton: '#7B8B8B',
    backGroundF4: '#F4F4F4',
  },
  fonts: {
    poppinsLight: 'Poppins Light',
    poppinsRegular: 'Poppins Regular',
    poppinsMedium: 'Poppins Medium',
    poppinsBold: 'Poppins Bold',
    poppinsBlack: 'Poppins Black',
    poppinsSemiBold: 'Poppins SemiBold',
  },
};
